# src/features/regime.py
import pandas as pd
import numpy as np
import logging

class TemporalFeatureEngineer:
    """
    Generates rolling volatility and panic indices.
    STRICT LEAKAGE PREVENTION: STL Decomposition removed. 
    All rolling windows explicitly enforced with closed='right' / center=False.
    """
    def __init__(self, vol_window: int = 30, panic_window: int = 7):
        self.vol_window = vol_window
        self.panic_window = panic_window

    def _compute_features(self, group: pd.DataFrame) -> pd.DataFrame:
        group = group.sort_values('date').copy()
        
        # 1. Log Returns
        group['log_return'] = np.log(group['price'] / group['price'].shift(1))
        
        # 2. Rolling Volatility (strictly backward)
        group['volatility_30d'] = group['log_return'].rolling(window=self.vol_window, min_periods=self.vol_window).std()
        
        # 3. 7-Day Panic Index (strictly backward, upward momentum only)
        group['velocity_7d'] = (group['price'] - group['price'].shift(self.panic_window)) / group['price'].shift(self.panic_window)
        group['positive_return'] = (group['log_return'] > 0).astype(int)
        group['momentum_7d'] = group['positive_return'].rolling(window=self.panic_window, min_periods=self.panic_window).sum()
        
        group['panic_index_7d'] = np.where(
            group['velocity_7d'] > 0,
            group['velocity_7d'] * (1 + (group['momentum_7d'] / self.panic_window)),
            0
        )
        
        # LEAKAGE FIX: STL decomposition completely removed from this global phase.
        
        return group

    def process(self, df: pd.DataFrame) -> pd.DataFrame:
        logging.info("Initiating Leakage-Free Temporal Feature Engineering...")
        if df.empty:
            raise ValueError("Feature Engineer received an empty DataFrame.")
            
        engineered_chunks = []
        for (market, crop), group in df.groupby(['market', 'crop']):
            processed_group = self._compute_features(group)
            engineered_chunks.append(processed_group)
            
        engineered_df = pd.concat(engineered_chunks, ignore_index=True)
        
        # Drop the initial NaN artifact rows generated by the backward rolling windows
        engineered_df = engineered_df.dropna(subset=['volatility_30d', 'panic_index_7d'])
        
        logging.info(f"Phase 2 Complete. Generated {len(engineered_df)} strictly historical regime records.")
        return engineered_df.reset_index(drop=True)