import os
import logging
import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine
from statsmodels.tsa.seasonal import STL

# Configure production-grade logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class TemporalFeatureEngineer:
    """
    Constructs regime-aware exogenous features for time-series forecasting.
    Strictly avoids look-ahead bias by using localized, right-aligned rolling windows.
    """
    def __init__(self):
        load_dotenv()
        self.db_user = os.getenv("DB_USER", "postgres")
        self.db_password = os.getenv("DB_PASSWORD")
        self.db_host = os.getenv("DB_HOST", "localhost")
        self.db_port = os.getenv("DB_PORT", "5432")
        self.db_name = os.getenv("DB_NAME", "postgres")
        
        if not self.db_password:
            raise ValueError("CRITICAL ERROR: DB_PASSWORD environment variable is missing.")
            
        self.db_url = f"postgresql://{self.db_user}:{self.db_password}@{self.db_host}:{self.db_port}/{self.db_name}"
        self.engine = create_engine(self.db_url)
        self.df = pd.DataFrame()

    def extract_data(self) -> None:
        """Pulls clean data from the PostgreSQL database."""
        logging.info("Extracting data from 'amis_clean_prices'...")
        query = "SELECT * FROM amis_clean_prices ORDER BY market, crop, date ASC"
        self.df = pd.read_sql(query, con=self.engine)
        
        # Enforce strict chronological datatypes
        self.df['date'] = pd.to_datetime(self.df['date'])
        logging.info(f"Extraction complete. Retrieved {len(self.df)} records.")

    def _apply_stl_decomposition(self, group: pd.DataFrame) -> pd.DataFrame:
        """
        Isolates trend, seasonality, and residuals using Loess smoothing.
        Period is set to 7 to capture weekly market trading seasonality.
        """
        group = group.set_index('date').asfreq('D')
        
        # Robust STL prevents black-swan anomalies from corrupting the seasonal baseline
        stl = STL(group['price'], period=7, robust=True)
        result = stl.fit()
        
        group['trend'] = result.trend
        group['seasonality'] = result.seasonal
        group['residual'] = result.resid
        
        return group.reset_index()

    def _extract_volatility(self, group: pd.DataFrame, window: int = 30) -> pd.DataFrame:
        """
        Calculates 30-day rolling standard deviation of log-returns.
        """
        group['log_return'] = np.log(group['price'] / group['price'].shift(1))
        # closed='right' ensures the current day's return is the final observation (no look-ahead)
        group['volatility_30d'] = group['log_return'].rolling(window=window, closed='right').std()
        return group

    def _construct_panic_index(self, group: pd.DataFrame, window: int = 7) -> pd.DataFrame:
        """
        Engineers a composite index of price velocity and upward momentum.
        """
        # Velocity: 7-day rate of change
        group['velocity_7d'] = group['price'].pct_change(periods=window)
        
        # Momentum: Count of positive daily returns over the last 7 days
        is_positive_return = (group['log_return'] > 0).astype(int)
        group['momentum_7d'] = is_positive_return.rolling(window=window, closed='right').sum()
        
        # Composite Panic Index: Only triggers for upward velocity. Downward is correction, not panic.
        group['panic_index_7d'] = np.where(
            group['velocity_7d'] > 0,
            group['velocity_7d'] * (1 + (group['momentum_7d'] / window)),
            0
        )
        return group

    def _process_market_crop_group(self, group: pd.DataFrame) -> pd.DataFrame:
        """Applies the mathematical transformations to an isolated group."""
        group = self._apply_stl_decomposition(group)
        group = self._extract_volatility(group)
        group = self._construct_panic_index(group)
        return group

    def build_and_load_feature_store(self) -> None:
        """
        Executes the feature engineering pipeline and pushes to the database.
        """
        if self.df.empty:
            raise RuntimeError("Dataframe is empty. Run extract_data() first.")

        logging.info("Initiating strict Temporal Feature Engineering pipeline...")
        
        # Apply transformations strictly grouped by market and crop to prevent bleed
        processed_df = self.df.groupby(['market', 'crop'], group_keys=False).apply(self._process_market_crop_group)
        
        # Drop the initial NaN artifact rows generated by the rolling window calculations
        processed_df.dropna(inplace=True)
        
        # Load the feature-rich data into the new PostgreSQL table
        logging.info("Loading exogenous features into 'amis_market_features'...")
        processed_df.to_sql('amis_market_features', con=self.engine, if_exists='replace', index=False)
        logging.info("Phase 2 Execution Complete. Feature store is live.")

if __name__ == "__main__":
    try:
        engineer = TemporalFeatureEngineer()
        engineer.extract_data()
        engineer.build_and_load_feature_store()
    except Exception as e:
        logging.error(f"Pipeline Failed: {e}")